### ISSUE TITLE
bug in report_progress() - problem with aggregate()

### ISSUE THREAD

**Issue by konradmayer** [emilyriederer/projmgr#12]
As `aggregate()` coerces to factor the ordering of groups doesn't necessary match the ordering of milestone_title.

https://github.com/emilyriederer/projmgr/blob/341c2a96ce2f0841877b298ed5806645f30c543b/R/report.R#L32-L35

https://github.com/emilyriederer/projmgr/blob/341c2a96ce2f0841877b298ed5806645f30c543b/R/report.R#L45-L47

I will file a PR as soon as I find time for it.

**Comment by emilyriederer** [comment]
Thank you so much for flagging this an ever more for going ahead and diagnosing the root cause! To be honest, I did not know that about `aggregate()` so it might have taken me some time to figure this out (once I even found the error!)

I had some time, so I went ahead and put into a fix before any more potential users stumble across the incorrect version. I really appreciate the contribution and your taking the time to report. I added a shout-out of gratitude the `README`  / site homepage. 🙂

**Comment by konradmayer** [comment]
Not worth mentioning. Reporting bugs is the best way to reciprocate to people offering amazing open source software - thanks for a great package!

**Comment by emilyriederer** [comment]
Honestly, it means a ton to me that anyone was interested enough in the package to look at it, and even more to take the time to comment and help out so much! This is my first real open source effort, so I'm just thrilled if its of use to anyone 😄
